apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuralscope-server
  namespace: neuralscope
  labels:
    app: neuralscope-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neuralscope-server
  template:
    metadata:
      labels:
        app: neuralscope-server
    spec:
      containers:
        - name: server
          image: ghcr.io/panditdhamdhere/neuralscope/server:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: neuralscope-config
            - secretRef:
                name: neuralscope-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
