apiVersion: v1
kind: Service
metadata:
  name: neuralscope-server
  namespace: neuralscope
spec:
  selector:
    app: neuralscope-server
  ports:
    - port: 8080
      targetPort: 8080
      name: http
